version: "3"
services:
  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    extra_hosts:
      - "host.docker.internal:host-gateway"

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - loki

  prometheus:
    image: prom/prometheus:v2.30.0
    volumes:
      - ./docker/prometheus/config:/etc/prometheus
      - ./docker/prometheus/data:/prometheus
    ports:
      - 9090:9090
    networks:
      - loki
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  grafana-storage:

networks:
  loki:

