version: '3.9'
services:
  besu-4:
    container_name: besu-4
    network_mode: "host"
    image: hyperledger/besu:22.4.1
    environment:
      - BESU_CONFIG_FILE=/config/besu/config.toml
    volumes:
      - ./config/besu/config4.toml:/config/besu/config.toml
      - ./IBFT-Network/genesis.json:/config/besu/genesis.json
      - ./IBFT-Network/Node-4/data:/opt/besu/data
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    # depends_on:
    #   - fluent-bit
# fluent-bit:
#   container_name: fluent-bit
#   network_mode: "host"
#   image: grafana/fluent-bit-plugin-loki:latest
#   environment:
#     - "LOKI_URL=http://{loki_ip}:3100/loki/api/v1/push"
#   volumes:
#     - ./docker/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf