  version: "3.9"
  services:
    fluent-bit:
      container_name: fluent-bit
      network_mode: "host"
      image: grafana/fluent-bit-plugin-loki:latest
      environment:
        - "LOKI_URL=http://localhost:3100/loki/api/v1/push"
      volumes:
        - ./docker/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    #   ports:
    #     - "24224:24224"
    #     - "24224:24224/udp"