version: "3"
services:
  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    extra_hosts:
      - "host.docker.internal:host-gateway"

  promtail:
    image: grafana/promtail:2.6.1
    # volumes:
    #   - ./docker/logs:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - loki

  prometheus:
    image: prom/prometheus:v2.30.0
    volumes:
      - ./docker/prometheus/config:/etc/prometheus
      - ./docker/prometheus/data:/prometheus
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
    networks:
      - loki
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - loki
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - loki
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  grafana-storage:

networks:
  loki:

